include ../BuildSystem/CommonDefs.mak

BIN_DIR = ../Bin

INC_DIRS = \
	../../Include

SRC_FILES = *.cpp

USED_LIBS += OpenNI2

EXE_NAME = MultipleStreamRead

CFLAGS += -Wall

include ../BuildSystem/CommonCppMakefile
