include ../BuildSystem/CommonDefs.mak

BIN_DIR = ../Bin

INC_DIRS = \
	../../Include \
	../MWClosestPoint

SRC_FILES = *.cpp

USED_LIBS += OpenNI2 MWClosestPoint

EXE_NAME = MWClosestPointApp

CFLAGS += -Wall

include ../BuildSystem/CommonCppMakefile
